name: Publish

on:
  pull_request:
    types: [closed]
  workflow_dispatch:
    inputs:
      release:
        description: Is this a major, minor or patch release?
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

defaults:
  run:
    shell: pwsh

jobs:
  publish:
    if: ${{
          github.event.workflow || (
            github.event.pull_request.merged &&
            github.event.pull_request.base.ref == 'main' && (
              contains(github.event.pull_request.labels.*.name, 'release-major') ||
              contains(github.event.pull_request.labels.*.name, 'release-minor') ||
              contains(github.event.pull_request.labels.*.name, 'release-patch') ) ) }}
    uses: fsackur/ci/.github/workflows/publish-powershell.yml@main
    with:
      event_json: ${{ toJson(github.event) }}
    secrets: inherit
